language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

notifications:
  webhooks:
    - http://jenkins.opsgenie.com:11000/v1/json/travisci?apiKey=c9976b41-d97e-42a4-b862-f54f9a9165ee
  on_start: true