language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

notifications:
  webhooks:
    - http://jenkins.opsgenie.com:11000/v1/json/travisci?apiKey=6cd90689-d1e2-4408-bda5-37357b2629a1
  on_start: true
  on_success: always
  on_failure: always