language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

notifications:
  webhooks:
    - http://jenkins.opsgenie.com:11000/v1/json/travisci?apiKey=47f9efe9-2c08-45c7-871d-8dc1a7bf71b8
  on_start: true