language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

notifications:
  webhooks:
    - http://office.ifountain.com/v1/json/travisci?apiKey=81ca4354-8f80-46ab-8446-f9ef2209ad3c
  on_start: true
  on_success: always
  on_failure: always