language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

notifications:
  webhooks: http://requestb.in/10rbzwf1
    on_success: always # default: always
    on_failure: always # default: always
    on_start: true # default: false
			